# Generated by Django 2.0.2 on 2018-11-16 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReview', '0011_auto_20181008_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieinfo',
            options={'ordering': ('movie_name',)},
        ),
    ]
